baseurl = "https://skipkrueger.com/"
title = "Skip Krueger"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Data scientist and scholar"
  copyright = "&copy;2020 Skip Krueger"
  sidebarAbout = [
    "Data scientist, associate professor, passionate advocate for public service.",
    "Specializing in state and local public finance, local political economy, and fiscal effects of disasters.",
#    "Currently a tenured associate professor of public administration in Denton, Texas.",
    "<BR>","<BR>","<BR>","<BR>","<BR>","<BR>","<BR>","<BR>"
    ]
#  email = "you@yoursite.com"

  [[params.navlinks]]
  name = "Home"
  url = "post/"
  home = true

#  name = "About"
#  url = "about/"

#  name = "Get in touch"
#  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/skip.krueger.589"
#  email         = "email@example.com"
  twitter       = "https://twitter.com/KruegerSkip"
  linkedin      = "https://www.linkedin.com/in/skip-krueger-39a3b9153/"

    


    